# Generated by Django 2.1.2 on 2018-11-20 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TA_Scheduling_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(default='None', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.CharField(default='None', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.CharField(default='None', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
                ('labs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TA_Scheduling_App.Lab')),
            ],
        ),
        migrations.CreateModel(
            name='TA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ta', models.CharField(default='None', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='assignment',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='course',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='firstname',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='lab',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='lastname',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='relationship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TA_Scheduling_App.Account'),
        ),
        migrations.AddField(
            model_name='class',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TA_Scheduling_App.Instructor'),
        ),
        migrations.AddField(
            model_name='class',
            name='labs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TA_Scheduling_App.Lab'),
        ),
        migrations.AddField(
            model_name='class',
            name='ta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TA_Scheduling_App.TA'),
        ),
    ]
