# Generated by Django 2.1.2 on 2018-11-20 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TA_Scheduling_App', '0002_auto_20181120_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='instructor',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='TA_Scheduling_App.Instructor'),
        ),
        migrations.AlterField(
            model_name='class',
            name='labs',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='TA_Scheduling_App.Lab'),
        ),
        migrations.AlterField(
            model_name='class',
            name='ta',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='TA_Scheduling_App.TA'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='course',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='labs',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='TA_Scheduling_App.Lab'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='user',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='TA_Scheduling_App.Account'),
        ),
    ]
