# Generated by Django 2.1.2 on 2018-12-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TA_Scheduling_App', '0005_auto_20181126_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='officehours',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
